### ISSUE TITLE
how to set local assets

### ISSUE THREAD

**Issue by DansDesigns** [Srajan04/Cinemate#1]
Hey, thank you for this!
It looks exactly like what I need!

I'm having some trouble figuring out how to change the following in order to reference the file structure:
```
# Set the OUTPUT_PATH to the parent directory of the current script
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / \
    Path(r" ")  # Set the ASSETS_PATH to the tS folder

# Define a function to create a Path object relative to ASSETS_PATH


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)
```

In previous python programs i have used similar to this to reference local files:
```
model = Model(r'C:\users\<USERNAME>\PycharmProjects\Vosk_AI\modules\EN')  # Modul folder
``` 
however when i run with the "Path(r" ")" including my local folders, i get this:
```
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\C:\\Users\\<USERNAME>\\PycharmProjects\\Cinemate-main\\cinemate ss.png'
```

any guidance would be greatly appreciated

**Comment by DansDesigns** [comment]
ok so fixing the above error give this now:
```
 File "C:\Users\Dan\PycharmProjects\Cinemate-main\mainTK.py", line 112, in acc_create
    with open(filename, 'r+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\SRAJAN\\Python\\DSA Sem-3 Cinemate Project\\userdata.json'
```

i found the culprit line 63:
```
 def user_data(x):  # Define a function to store the user data in a json file
        filename = r'D:\SRAJAN\Python\DSA Sem-3 Cinemate Project\userdata.json'
```
and line 75:

```
filename = r'D:\SRAJAN\Python\DSA Sem-3 Cinemate Project\userdata.json'
```

**Comment by Srajan04** [comment]
Yes, I should have mentioned that in Readme, but since this was a college project, it completely left my mind, cause of the submission rush.

**Comment by Srajan04** [comment]
Basically for the `Path(r" ")`, you just need to put full your complete Non-Relative path of the assets folder. and change paths in `filename`. (which you firgured out)
